### PR TITLE
Added XEP-0138 Stream Compression support to XMPPFramework

### PR DESCRIPTION
**Pull request by sprhawk**
1. Separated XMPPStream internal Extension into the XMPPStreamInternal.h, which could be called from XMPPFeature;
    2. Moved asyncSocket write/read data into a wrapper method -[XMPPStream write/readData ...], in which a registeredStreamPreprocessor could do preprocess (eg, XMPPCompression could deflate / inflate data);
    3. Added XMPPFeature into calling procedure for XMPPStream;
    4. Added XMPPCompression feature, which applies to XEP-0138 Stream Compression
    5. Added XMPPCompression support into DesktopXMPP and iPhoneXMPP projects

Tested on OpenFire 3.8.2 and ejabbared 2.1.13

### CODE REVIEW

**Comment by am33t** [comment]
I have identified 2 problems here.
First, Inflation failed: -3(invalid code lengths set) OR -3(invalid distance too far back) 
you get this error because the packet size to be decompressed is over 1024. You can fix this by increasing size of buffer    
Bytef output[4096];  //Method processInputData:
but, this will still happen if packet size is over 4096

Second, because of first error, method "processInputData:" doesn't give proper uncompressed data. This is why xml packet parser fails to parse and disconnects XMPP.

After this XMPPCompression does send stream error and ends streams but continues sending compressed packets. Session cant be created because server is expecting uncompressed data but client is sending compressed data. And server keeps on sending XML error. (xml-not-well-formed)

thanks

**Comment by sprhawk** [comment]
@am33t Thank you for your comments. I was not focused on this stuff for a long time.

I may have found the problem : that is 

    offset += blockSz; 

in processInputData method, changed with:

    _inflation_strm.total_in - old_total_in;

**Comment by sprhawk** [comment]
I accidently removed the branch and it caused this pull request closed. please add new comment to #563

**Comment by sprhawk** [comment]
@wujie0919 you can try the new commits if you have spare time

**Comment by sprhawk** [comment]
@goodleixiao please try the new commits from my own repo

**Pull request closed without merging**
