### PR TITLE
Fixed Podspec + Swift support  

### PR DESCRIPTION
**Pull request by baoluo**
Fixed dns_sd and libxml2 import (modulemap file addition) + fixed circular import in podspec with full swift support

### CODE REVIEW

**Comment by chrisballinger** [comment]
@baoluo Thank you!

**Comment by chrisballinger** [comment]
@baoluo Have you seen #591? Does this PR address that issue or do we need to fix it?

**Comment by baoluo** [comment]
Hello Chris !

I’m glad to hear that you like it !

This issue is indeed fixed, you can close it :)

Paul

**Comment by powerqian** [comment]
Hi @baoluo , the Podspec you write is great. However it includes the KissXML library entirely in the code because of those defines in DDXML.h. In my project, I use other Pod which has KissXML as its dependency. As a result, there will be conflict for the KissXML. Is there any reasonable fix for that? Maybe use the KissXML as dependency as well, in which case CocoaPods will solve the conflict itself.

**Comment by baoluo** [comment]
Hello @powerqian, Unfortunately the KissXML dependency is embedded inside the XMPPFramework, so if we want to add it as dependency we have to modify the XMPPFramework itself, then edit the Podspec to reflect the changes. I asked myself the question of doing so when I fixed the Podespec, but I decided that it wasn't the priority at the moment. For now I can't handle it myself, but maybe others like @chrisballinger  can do it.

**Comment by powerqian** [comment]
@chrisballinger any thoughts of doing so? I notice that the KissXML repo has recent changes by you despite that the tag of the project which the `podspec` in CocoaPods points to is ancient. 

You can make KissXML available for this XMPPFramework library to reference as a dependency in CocoaPods by
1. Remove the `&& 0` in `DDXML.h`.
2. Have a new tag and update the `podspec`.

It would be really helpful if you could do so!

**Comment by derbshireram** [comment]
Please revert this change! This change completely breaks the non-Cocoapod builds (for example, try to compile the sample iPhoneXMPP app from a fresh git clone and it fails with errors on import).

**Comment by powerqian** [comment]
@derbshireram There's a modulemap file. You just need to add that modulemap to the sample project settings. The sample project does need to have an update.

**Comment by derbshireram** [comment]
@powerqian I added it but still same error: Module 'libxmlSimu' not found. Maybe I'm not adding the modulemap file right? How am I supposed to add it to the settings? What settings am I changing?

**Comment by powerqian** [comment]
@derbshireram Try to add the path of the modulemap file to your "Header Search Path" in the project's Build Settings

**Comment by derbshireram** [comment]
@powerqian I tried that and it did not work. Still same error unfortunately. Does this really work for you? I'm using latest Xcode 7.1. Only I can compile is to back out this change. Thanks.

**Comment by powerqian** [comment]
@derbshireram Yes it works for me. Make sure your header path correctly points to the location of the modulemap file, and make sure your project enabled module (in Build Settings, search for modules, and set Enable Modules to YES). After that it should not have errors related to module.

**Comment by RicardCampanya** [comment]
@powerqian  HI, excuse me, but how can I  add the header path  and what path ? I have the modulemap file in projectroot/module
Another question is, the podspec file must has the podspec extension? 
i'm having errors with  @import lixmlsimu in ddxmlnode.h
Thanks a lot!

**Pull request merged**
