### PR TITLE
Invite multiple users

### PR DESCRIPTION
**Pull request by beribas**
Initing multiple users becomes handy if you can do it with one IQ.
This PR adds method to XMPPRoom which allows this.

### CODE REVIEW

**Comment by chrisballinger** [comment]
@beribas Thanks! Could you make the old method a wrapper for the new one so the code is shared?

**Comment by beribas** [comment]
@chrisballinger Sure, that's a good idea!

**Comment by chrisballinger** [comment]
Awesome, thank you!

**Comment by beribas** [comment]
You're welcome! Thank you for the framework! ;)

**Pull request merged**
