### PR TITLE
[WIP] Added Carthage support

### PR DESCRIPTION
**Pull request by dodikk**
# Implemented

* Added framework target
* Added workspace
* Added Cartfile with dependencies
* Configured dependencies for xcode project

# Not Implemented
Stuck at bitcode error for libidn
```
ld: '../../Vendor/libidn/libidn.a(stringprep.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The library should be rebuilt with the following flags
fembed-bitcode

### CODE REVIEW

**Comment by chrisballinger** [comment]
@dodikk Ideally we wouldn't ship a binary blob anyway. Maybe you could make a Carthage framework for https://github.com/chrisballinger/libidn-podspec

I never finished it though so it didn't fully work to integrate with XMPPFramework.

**Comment by dodikk** [comment]
> Maybe you could make a Carthage framework 

Sorry, no luck so far due to compiler errors in the unwrapped macros
https://github.com/chrisballinger/libidn-podspec/pull/3

**Comment by chrisballinger** [comment]
@dodikk KissXML should be Carthage compatible now.

**Comment by chrisballinger** [comment]
@dodikk I fixed up KissXML and libidn. In theory it should be possible to add Carthage support now, as of this commit: https://github.com/robbiehanson/XMPPFramework/commit/62bc48940e89bbcb6fac9a07b08ae3df89ccd5a3

**Comment by dodikk** [comment]
>> I fixed up KissXML and libidn. In theory it should be possible to add Carthage support now

Good news. Are any actions from my side required?

**Comment by dodikk** [comment]
> I fixed up KissXML and libidn. In theory it should be possible to add Carthage support now

I've updated the `Cartfile` in the pull request.

**Comment by dodikk** [comment]
# A quick reminder 

1. Please don't forget to change cartfile dependencies for libidn and kissxml when you make the tags and github releases for them.
2. The cartfile should be updated every time the podspec is changed in order to keep them consistent and synchronized.

P.S. Sorry if the last comment was too obvious or stupid.

**Comment by chrisballinger** [comment]
@dodikk No problem, thanks for your help!

**Comment by dodikk** [comment]
"Carthage for extensions" ticket https://github.com/robbiehanson/XMPPFramework/issues/881

**Pull request merged**
