### PR TITLE
Converting to modern Obj-C syntax for better Swift compatibility

### PR DESCRIPTION
**Pull request by chrisballinger**
This will require a major version bump because it will slightly break existing Swift code, but it provides major ergonomic gains (nullability, generics, properties). Existing Obj-C code should compile without any issues.

Right now I've only audited/annotated the files in `Core/` and `Categories/`. Ideally we should get as many breaking changes for the most popular modules into this PR as possible to minimize any future compatibility issues. If these changes will affect you, please comment below if you have any thoughts.. or see any annotation mistakes.

Thanks!

### Migration from 3.7 to 4.0

There have been a number of changes to the public API of XMPPFramework in an attempt to improve the ergnomics and safety when used with Swift. Most Objective-C projects should require no changes, with a few minor exceptions. Many (simple) changes will be required for pure Swift projects, mostly due to the new nullability annotations. The process is still not complete so please submit issues and help if possible to minimize future breaking changes.

* Modern Objective-C Syntax: Nullability annotations and generics.
* Most of Core, Authentication, Categories, and Utilities have been audited. Additional help is needed for Extensions.
* XMPPJID `bareJID` is now imported into Swift as `bareJID` instead of `bare` to prevent conflict with `bare` String. Also applies to `domainJID`.
* XMPPPresence `intShow` has been renamed `showValue` and is now an `XMPPPresenceShow` enum instead of `int`. This will be a warning in 4.0 but will be removed in 4.1.
* Readonly properties are used instead of getter methods where applicable. Getter naming overrides for properties have been removed to reflect Apple's approach.
* The following modules still need an audit. If you use these modules please help out and contribute some time to audit them and submit a pull request, otherwise their API may contain breaking changes in future releases.

	* XEP-0191 Blocking
	* XEP-0199 Ping
	* XEP-0202 Time
	* XEP-0136 Archiving
	* XEP-0115 Capabilities (CoreDataStorage unaudited)
	* XEP-0045 MUC (Storage unaudited)
	* XEP-0054 vCardTemp (CoreDataStorage unaudited)
	* XEP-0016 Privacy
	* XEP-0012 Last Activity
	* XEP-0009 RPC
	* Roster (Storage unaudited)
	* XMPPGoogleSharedStatus
	* FileTransfer
	* CoreDataStorage
	* BandwidthMonitor

### CODE REVIEW

**Comment by pwetrifork** [comment]
We like the direction, one additional thing to consider would be annotating initalizers with `NS_DESIGNATED_INITIALIZER`/`NS_UNAVAILABLE`.
The latter in particular is useful in cases where parameterless initializer should not be used; without the annotation a class will inherit it from NSObject and we can end up with an instance with nulls for properties that are marked nonnull in the interface.

**Comment by chrisballinger** [comment]
@pwetrifork Oh yeah good call. Would you like to volunteer to audit some of the extensions? ;)

**Comment by pwetrifork** [comment]
I am sorry but I can't make any commitments now (i.e. in the coming 2-3 months).

**Comment by chrisballinger** [comment]
No problem. Thanks for your contributions!

**Pull request merged**
